### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by GFTNROC** [Mabi19/password-game-tas#3] opened 2023-08-04 16:46 UTC
userscript.html?name=Password-Game-TAS.user.js&id=e391db53-d0f2-4f8a-8d03-6368d34b1330:12 TypeError: Cannot read properties of null (reading 'src')
    at s0 (userscript.html?name=Password-Game-TAS.user.js&id=e391db53-d0f2-4f8a-8d03-6368d34b1330:12:58289)
    at async l (userscript.html?name=Password-Game-TAS.user.js&id=e391db53-d0f2-4f8a-8d03-6368d34b1330:12:130793)
    at async S (userscript.html?name=Password-Game-TAS.user.js&id=e391db53-d0f2-4f8a-8d03-6368d34b1330:12:133242)

**Comment by Mabi19** [comment] 2023-08-08 08:27
Duplicate of #1

**Closed by Mabi19** 2023-08-08 08:27 UTC
